# Generated by Django 4.2.4 on 2023-09-03 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=255)),
                ('ulchov_briligi', models.CharField(max_length=255)),
                ('miqdori', models.IntegerField()),
                ('narxi', models.IntegerField()),
                ('summasi', models.IntegerField()),
            ],
        ),
    ]
